//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;

    [Table("PlayerList")]
    public partial class PlayerList
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string account { get; set; }
        public string pwd { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string DeliveryAddress { get; set; }
        [DefaultValue(typeof(DateTime), "")]
        public System.DateTime birthday { get; set; }
        public string hobbies { get; set; }
        [DefaultValue(0)]
        public int income { get; set; }
        [DefaultValue("none")]
        public string avatar { get; set; }
    }
}
