//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    [Table(("shoppingCart"))]
    public partial class User_shoppingCart
    {
        [Key]
        public int id { get; set; }

        public string account { get; set; }

        public int item { get; set; }

        public int count { get; set; } = 0;

        [Column("type")]
        [DefaultValue("default")]
        public string type { get; set; }

        [ForeignKey(nameof(item))]
        public virtual babys babys { get; set; }

    }
}
